name: Add comment to successful Dependabot PRs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          use-github-auto-merge: true
